[server]
protocol = http
http_port = 3000
root_url = %(protocol)s://%(domain)s:%(http_port)s/
# domain = ${DOMAIN_NAME}

[security]


[auth.anonymous]
enabled = false

[snapshots]
external_enabled = false

[users]
allow_sign_up = false
allow_org_create = false

[auth]
disable_login_form = false

[log]
mode = console
level = info
